// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/data/repositories/baby_registration_repository/baby_registration_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:yuktoe/core/result.dart' as _i4;
import 'package:yuktoe/data/services/baby_registration_service/baby_registration_service.dart'
    as _i2;
import 'package:yuktoe/domain/models/baby_registration/baby_preview.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BabyRegistrationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBabyRegistrationService extends _i1.Mock
    implements _i2.BabyRegistrationService {
  MockBabyRegistrationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<String>> createBaby({
    required String? name,
    String? birthDate,
    String? dueDate,
    required String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBaby, [], {
              #name: name,
              #birthDate: birthDate,
              #dueDate: dueDate,
              #gender: gender,
            }),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i5.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#createBaby, [], {
                  #name: name,
                  #birthDate: birthDate,
                  #dueDate: dueDate,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<_i6.BabyPreview?>> verifyInviteCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyInviteCode, [code]),
            returnValue: _i3.Future<_i4.Result<_i6.BabyPreview?>>.value(
              _i5.dummyValue<_i4.Result<_i6.BabyPreview?>>(
                this,
                Invocation.method(#verifyInviteCode, [code]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i6.BabyPreview?>>);

  @override
  _i3.Future<_i4.Result<String>> joinBabyByInviteCode({
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinBabyByInviteCode, [], {#code: code}),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i5.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#joinBabyByInviteCode, [], {#code: code}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<void>> setupUserProfile({
    required String? babyId,
    required String? relationship,
    required String? nickname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setupUserProfile, [], {
              #babyId: babyId,
              #relationship: relationship,
              #nickname: nickname,
            }),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i5.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#setupUserProfile, [], {
                  #babyId: babyId,
                  #relationship: relationship,
                  #nickname: nickname,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
