// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/data/repositories/record_repository/record_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yuktoe/core/result.dart' as _i4;
import 'package:yuktoe/data/services/record_service/record_service.dart' as _i2;
import 'package:yuktoe/domain/models/common/page.dart' as _i7;
import 'package:yuktoe/domain/models/record/care_record.dart' as _i5;
import 'package:yuktoe/domain/models/record/record_memo.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecordService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordService extends _i1.Mock implements _i2.RecordService {
  MockRecordService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.CareRecord>> getRecord(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecord, [recordId]),
            returnValue: _i3.Future<_i4.Result<_i5.CareRecord>>.value(
              _i6.dummyValue<_i4.Result<_i5.CareRecord>>(
                this,
                Invocation.method(#getRecord, [recordId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.CareRecord>>);

  @override
  _i3.Future<_i4.Result<void>> updateRecord(
    String? recordId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecord, [recordId, data]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateRecord, [recordId, data]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteRecord(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecord, [recordId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteRecord, [recordId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i7.Page<_i8.RecordMemo>>> getMemos(
    String? recordId, {
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMemos,
              [recordId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue: _i3.Future<_i4.Result<_i7.Page<_i8.RecordMemo>>>.value(
              _i6.dummyValue<_i4.Result<_i7.Page<_i8.RecordMemo>>>(
                this,
                Invocation.method(
                  #getMemos,
                  [recordId],
                  {#cursor: cursor, #limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.Page<_i8.RecordMemo>>>);

  @override
  _i3.Future<_i4.Result<_i8.RecordMemo>> createMemo(
    String? recordId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMemo, [recordId, content]),
            returnValue: _i3.Future<_i4.Result<_i8.RecordMemo>>.value(
              _i6.dummyValue<_i4.Result<_i8.RecordMemo>>(
                this,
                Invocation.method(#createMemo, [recordId, content]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.RecordMemo>>);

  @override
  _i3.Future<_i4.Result<void>> updateMemo(String? memoId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemo, [memoId, content]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateMemo, [memoId, content]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteMemo(String? memoId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMemo, [memoId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteMemo, [memoId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
