// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/onboarding/view_models/invite_code_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:yuktoe/data/repositories/baby_registration_repository/baby_registration_repository.dart'
    as _i2;
import 'package:yuktoe/domain/models/baby_registration/baby_summary.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BabyRegistrationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBabyRegistrationRepository extends _i1.Mock
    implements _i2.BabyRegistrationRepository {
  MockBabyRegistrationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> createBaby({
    required String? name,
    String? birthDate,
    String? dueDate,
    required String? gender,
    required String? relationship,
    required String? nickname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBaby, [], {
              #name: name,
              #birthDate: birthDate,
              #dueDate: dueDate,
              #gender: gender,
              #relationship: relationship,
              #nickname: nickname,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#createBaby, [], {
                  #name: name,
                  #birthDate: birthDate,
                  #dueDate: dueDate,
                  #gender: gender,
                  #relationship: relationship,
                  #nickname: nickname,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<_i5.BabySummary?> verifyInviteCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyInviteCode, [code]),
            returnValue: _i3.Future<_i5.BabySummary?>.value(),
          )
          as _i3.Future<_i5.BabySummary?>);

  @override
  _i3.Future<String> joinBabyByInviteCode({
    required String? code,
    required String? relationship,
    required String? nickname,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinBabyByInviteCode, [], {
              #code: code,
              #relationship: relationship,
              #nickname: nickname,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#joinBabyByInviteCode, [], {
                  #code: code,
                  #relationship: relationship,
                  #nickname: nickname,
                }),
              ),
            ),
          )
          as _i3.Future<String>);
}
