// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/presentation/home/view_models/breast_stopwatch_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yuktoe/core/result.dart' as _i4;
import 'package:yuktoe/data/local/app_local_storage.dart' as _i10;
import 'package:yuktoe/data/repositories/record_repository/record_repository.dart'
    as _i2;
import 'package:yuktoe/domain/models/common/page.dart' as _i8;
import 'package:yuktoe/domain/models/record/care_record.dart' as _i5;
import 'package:yuktoe/domain/models/record/record_detail_data.dart' as _i7;
import 'package:yuktoe/domain/models/record/record_memo.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecordRepository extends _i1.Mock implements _i2.RecordRepository {
  MockRecordRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.CareRecord>> getRecord(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecord, [recordId]),
            returnValue: _i3.Future<_i4.Result<_i5.CareRecord>>.value(
              _i6.dummyValue<_i4.Result<_i5.CareRecord>>(
                this,
                Invocation.method(#getRecord, [recordId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.CareRecord>>);

  @override
  _i3.Future<_i4.Result<void>> updateRecord(
    String? recordId,
    _i7.RecordDetailData? detail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRecord, [recordId, detail]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateRecord, [recordId, detail]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteRecord(String? recordId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecord, [recordId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteRecord, [recordId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i8.Page<_i9.RecordMemo>>> getMemos(
    String? recordId, {
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMemos,
              [recordId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue: _i3.Future<_i4.Result<_i8.Page<_i9.RecordMemo>>>.value(
              _i6.dummyValue<_i4.Result<_i8.Page<_i9.RecordMemo>>>(
                this,
                Invocation.method(
                  #getMemos,
                  [recordId],
                  {#cursor: cursor, #limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.Page<_i9.RecordMemo>>>);

  @override
  _i3.Future<_i4.Result<_i9.RecordMemo>> addMemo(
    String? recordId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMemo, [recordId, content]),
            returnValue: _i3.Future<_i4.Result<_i9.RecordMemo>>.value(
              _i6.dummyValue<_i4.Result<_i9.RecordMemo>>(
                this,
                Invocation.method(#addMemo, [recordId, content]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i9.RecordMemo>>);

  @override
  _i3.Future<_i4.Result<void>> updateMemo(String? memoId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#updateMemo, [memoId, content]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateMemo, [memoId, content]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> deleteMemo(String? memoId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMemo, [memoId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteMemo, [memoId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<_i8.Page<_i5.CareRecord>>> getRecords(
    String? babyId, {
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecords,
              [babyId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue: _i3.Future<_i4.Result<_i8.Page<_i5.CareRecord>>>.value(
              _i6.dummyValue<_i4.Result<_i8.Page<_i5.CareRecord>>>(
                this,
                Invocation.method(
                  #getRecords,
                  [babyId],
                  {#cursor: cursor, #limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.Page<_i5.CareRecord>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.CareRecord>>> getRecentFeedings(
    String? babyId, {
    int? limit = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentFeedings, [babyId], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.CareRecord>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.CareRecord>>>(
                this,
                Invocation.method(
                  #getRecentFeedings,
                  [babyId],
                  {#limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.CareRecord>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.CareRecord>>> getRecentDiapers(
    String? babyId, {
    int? limit = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentDiapers, [babyId], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.CareRecord>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.CareRecord>>>(
                this,
                Invocation.method(#getRecentDiapers, [babyId], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.CareRecord>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.CareRecord>>> getRecentWakes(
    String? babyId, {
    int? limit = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentWakes, [babyId], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.CareRecord>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.CareRecord>>>(
                this,
                Invocation.method(#getRecentWakes, [babyId], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.CareRecord>>>);

  @override
  _i3.Future<_i4.Result<_i5.CareRecord>> createRecord(
    String? babyId,
    _i7.RecordDetailData? detail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRecord, [babyId, detail]),
            returnValue: _i3.Future<_i4.Result<_i5.CareRecord>>.value(
              _i6.dummyValue<_i4.Result<_i5.CareRecord>>(
                this,
                Invocation.method(#createRecord, [babyId, detail]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.CareRecord>>);
}

/// A class which mocks [AppLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalStorage extends _i1.Mock implements _i10.AppLocalStorage {
  MockAppLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setSelectedBabyId(String? babyId) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedBabyId, [babyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeSelectedBabyId() =>
      (super.noSuchMethod(
            Invocation.method(#removeSelectedBabyId, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setQuickLogButtonsJson(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setQuickLogButtonsJson, [json]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeQuickLogButtonsJson() =>
      (super.noSuchMethod(
            Invocation.method(#removeQuickLogButtonsJson, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
