// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/presentation/home/view_models/home_baby_info_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yuktoe/core/result.dart' as _i4;
import 'package:yuktoe/data/local/app_local_storage.dart' as _i8;
import 'package:yuktoe/data/repositories/baby_repository/baby_repository.dart'
    as _i2;
import 'package:yuktoe/domain/models/baby/baby.dart' as _i7;
import 'package:yuktoe/domain/models/baby/baby_list_item.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BabyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBabyRepository extends _i1.Mock implements _i2.BabyRepository {
  MockBabyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.BabyListItem>>> getMyBabies() =>
      (super.noSuchMethod(
            Invocation.method(#getMyBabies, []),
            returnValue: _i3.Future<_i4.Result<List<_i5.BabyListItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.BabyListItem>>>(
                this,
                Invocation.method(#getMyBabies, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.BabyListItem>>>);

  @override
  _i3.Future<_i4.Result<_i7.Baby>> getBaby(String? babyId) =>
      (super.noSuchMethod(
            Invocation.method(#getBaby, [babyId]),
            returnValue: _i3.Future<_i4.Result<_i7.Baby>>.value(
              _i6.dummyValue<_i4.Result<_i7.Baby>>(
                this,
                Invocation.method(#getBaby, [babyId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.Baby>>);
}

/// A class which mocks [AppLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalStorage extends _i1.Mock implements _i8.AppLocalStorage {
  MockAppLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setSelectedBabyId(String? babyId) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedBabyId, [babyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeSelectedBabyId() =>
      (super.noSuchMethod(
            Invocation.method(#removeSelectedBabyId, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setQuickLogButtonsJson(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setQuickLogButtonsJson, [json]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeQuickLogButtonsJson() =>
      (super.noSuchMethod(
            Invocation.method(#removeQuickLogButtonsJson, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
