// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/presentation/analytics/view_models/chat_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yuktoe/core/result.dart' as _i4;
import 'package:yuktoe/data/repositories/baby_repository/baby_repository.dart'
    as _i10;
import 'package:yuktoe/data/repositories/chat_repository/chat_repository.dart'
    as _i2;
import 'package:yuktoe/domain/models/baby/baby.dart' as _i12;
import 'package:yuktoe/domain/models/baby/baby_list_item.dart' as _i11;
import 'package:yuktoe/domain/models/chat/chat_conversation.dart' as _i5;
import 'package:yuktoe/domain/models/chat/chat_message.dart' as _i7;
import 'package:yuktoe/domain/models/chat/chat_stream_event.dart' as _i8;
import 'package:yuktoe/domain/models/chat/suggested_questions.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i2.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.ChatConversation>>> getConversations(
    String? babyId, {
    String? cursor,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getConversations,
              [babyId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.ChatConversation>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.ChatConversation>>>(
                    this,
                    Invocation.method(
                      #getConversations,
                      [babyId],
                      {#cursor: cursor, #limit: limit},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.ChatConversation>>>);

  @override
  _i3.Future<_i4.Result<List<_i7.ChatMessage>>> getMessages(
    String? conversationId, {
    String? cursor,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [conversationId],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue: _i3.Future<_i4.Result<List<_i7.ChatMessage>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.ChatMessage>>>(
                this,
                Invocation.method(
                  #getMessages,
                  [conversationId],
                  {#cursor: cursor, #limit: limit},
                ),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.ChatMessage>>>);

  @override
  _i3.Stream<_i8.ChatStreamEvent> sendMessage({
    required String? babyId,
    String? conversationId,
    required String? text,
    required DateTime? localDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #babyId: babyId,
              #conversationId: conversationId,
              #text: text,
              #localDate: localDate,
            }),
            returnValue: _i3.Stream<_i8.ChatStreamEvent>.empty(),
          )
          as _i3.Stream<_i8.ChatStreamEvent>);

  @override
  _i3.Future<_i4.Result<_i9.SuggestedQuestions>> getSuggestions(
    String? babyId,
    DateTime? localDate,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSuggestions, [babyId, localDate]),
            returnValue: _i3.Future<_i4.Result<_i9.SuggestedQuestions>>.value(
              _i6.dummyValue<_i4.Result<_i9.SuggestedQuestions>>(
                this,
                Invocation.method(#getSuggestions, [babyId, localDate]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i9.SuggestedQuestions>>);

  @override
  String? activeConversationId(String? babyId) =>
      (super.noSuchMethod(Invocation.method(#activeConversationId, [babyId]))
          as String?);

  @override
  _i3.Future<void> setActiveConversationId(
    String? babyId,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveConversationId, [
              babyId,
              conversationId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearActiveConversation(String? babyId) =>
      (super.noSuchMethod(
            Invocation.method(#clearActiveConversation, [babyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [BabyRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBabyRepository extends _i1.Mock implements _i10.BabyRepository {
  MockBabyRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i11.BabyListItem>>> getMyBabies() =>
      (super.noSuchMethod(
            Invocation.method(#getMyBabies, []),
            returnValue: _i3.Future<_i4.Result<List<_i11.BabyListItem>>>.value(
              _i6.dummyValue<_i4.Result<List<_i11.BabyListItem>>>(
                this,
                Invocation.method(#getMyBabies, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i11.BabyListItem>>>);

  @override
  _i3.Future<_i4.Result<_i12.Baby>> getBaby(String? babyId) =>
      (super.noSuchMethod(
            Invocation.method(#getBaby, [babyId]),
            returnValue: _i3.Future<_i4.Result<_i12.Baby>>.value(
              _i6.dummyValue<_i4.Result<_i12.Baby>>(
                this,
                Invocation.method(#getBaby, [babyId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i12.Baby>>);
}
