// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/presentation/common/current_baby_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yuktoe/data/local/app_local_storage.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLocalStorage extends _i1.Mock implements _i2.AppLocalStorage {
  MockAppLocalStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setSelectedBabyId(String? babyId) =>
      (super.noSuchMethod(
            Invocation.method(#setSelectedBabyId, [babyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeSelectedBabyId() =>
      (super.noSuchMethod(
            Invocation.method(#removeSelectedBabyId, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String? activeConversationId(String? babyId) =>
      (super.noSuchMethod(Invocation.method(#activeConversationId, [babyId]))
          as String?);

  @override
  _i3.Future<void> setActiveConversationId(
    String? babyId,
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveConversationId, [
              babyId,
              conversationId,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeActiveConversationId(String? babyId) =>
      (super.noSuchMethod(
            Invocation.method(#removeActiveConversationId, [babyId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
