// Mocks generated by Mockito 5.4.6 from annotations
// in yuktoe/test/presentation/auth/login/login_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yuktoe/constants/enum/social_auth_provider.dart' as _i7;
import 'package:yuktoe/core/result.dart' as _i4;
import 'package:yuktoe/data/repositories/auth_repository/auth_repository.dart'
    as _i2;
import 'package:yuktoe/domain/models/auth/app_session.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i3.Future<_i4.Result<_i5.AppSession?>> getSession() =>
      (super.noSuchMethod(
            Invocation.method(#getSession, []),
            returnValue: _i3.Future<_i4.Result<_i5.AppSession?>>.value(
              _i6.dummyValue<_i4.Result<_i5.AppSession?>>(
                this,
                Invocation.method(#getSession, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.AppSession?>>);

  @override
  _i3.Future<_i4.Result<void>> signIn(_i7.SocialAuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [provider]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signIn, [provider]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
